- name: "find mysql history file"
  find:
    paths: /home
    patterns: ".mysql_history"
    file_type: file
    hidden: yes
    recurse: yes
  register: file_to_del
  tags:
    - cis1.3

- name: "Remove mysql_history file"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ file_to_del.files }}"
  tags:
    - cis1.3

- name: "create symlink"
  file:
    src: /dev/null
    dest: "{{ item.path }}"
    state: link
  with_items: "{{ file_to_del.files }}"
  tags:
    - cis1.3
  